version: 1.1.{build}
configuration:
  - Release
  - StaticRelease
  - Debug
install:
# download static qt if necessary
- ps: If ( $env:CONFIGURATION -eq "StaticRelease" ) { appveyor DownloadFile "https://github.com/fullincome/qtbase/releases/download/static_build/qtbase-static.zip" -FileName qtbase-static.zip }
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
- cmd: set QT_STATIC_DIR=C:\Qt\5.11.1\Static-5.11.1
- cmd: set QT_MINGW_DIR=C:\Qt\5.11.1\mingw53_32
- cmd: set PATH=%QT_MINGW_DIR%\bin;C:\MinGW\bin;%PATH%
- cmd: if not defined APPVEYOR_REPO_TAG_NAME set APPVEYOR_REPO_TAG_NAME=notag
- cmd: call build_win.bat
on_failure:
- ps: >-
    $blockRdp = $true;
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
- path: release/deploy/ca-lite.exe
  name: release_ca-lite
- path: static_release/deploy/ca-lite.exe
  name: static_release_ca-lite
- path: debug/deploy/ca-lite.exe
  name: debug_ca-lite
- path: $(APPVEYOR_REPO_TAG_NAME)_win32.zip
  name: $(APPVEYOR_REPO_TAG_NAME)_win32.zip
- path: $(APPVEYOR_REPO_TAG_NAME)-standalone_win32.zip
  name: $(APPVEYOR_REPO_TAG_NAME)-standalone_win32.zip
- path: $(APPVEYOR_REPO_TAG_NAME)-debug_win32.zip
  name: $(APPVEYOR_REPO_TAG_NAME)-debug_win32.zip
before_deploy:
- cmd: ''
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: boZUnfupnQ0mzFj+v+4IRwzDkWOm7uWf/4xzBEhEeztMFyf1AKNAVSQeJslJu+j1
  artifact: $(APPVEYOR_REPO_TAG_NAME)_win32.zip; $(APPVEYOR_REPO_TAG_NAME)-standalone_win32.zip
  draft: true
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true
