version: 1.1.{build}
environment:
  QTDIR: C:\Qt\5.11.1\mingw53_32
  PATH: '%PATH%;%QTDIR%\bin;C:\MinGW\bin'
build_script:
- cmd: >-
    set QT_MINGW_DIR=C:\Qt\5.11.1\mingw53_32

    set PATH=%PATH%;%QT_MINGW_DIR%\bin;C:\MinGW\bin

    if not defined APPVEYOR_REPO_TAG_NAME set APPVEYOR_REPO_TAG_NAME=notag


    mkdir release release\deploy
    
    cd release
    
    qmake.exe ..\ca-lite.pro -spec win32-g++

    mingw32-make.exe

    cd ..


    mkdir debug debug\deploy

    cd debug

    qmake.exe ..\ca-lite.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

    mingw32-make.exe

    cd ..

    copy .\release\ca-lite.exe .\release\deploy\ca-lite.exe
    
    %QT_MINGW_DIR%\windeploy.exe .\release\deploy\ca-lite.exe
    
    7z a %APPVEYOR_REPO_TAG_NAME%-release_win32.zip .\release\deploy\*
    
    copy .\debug\ca-lite.exe .\debug\deploy\ca-lite.exe
    
    %QT_MINGW_DIR%\windeploy.exe .\debug\deploy\ca-lite.exe

    7z a %APPVEYOR_REPO_TAG_NAME%-debug_win32.zip .\debug\deploy\*
artifacts:
- path: release/ca-lite.exe
  name: release_ca-lite
- path: debug/ca-lite.exe
  name: debug_ca-lite
- path: $(APPVEYOR_REPO_TAG_NAME)-release_win32.zip
  name: $(APPVEYOR_REPO_TAG_NAME)-release_win32.zip
- path: $(APPVEYOR_REPO_TAG_NAME)-debug_win32.zip
  name: $(APPVEYOR_REPO_TAG_NAME)-debug_win32.zip
before_deploy:
- cmd: ''
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: boZUnfupnQ0mzFj+v+4IRwzDkWOm7uWf/4xzBEhEeztMFyf1AKNAVSQeJslJu+j1
  artifact: $(APPVEYOR_REPO_TAG_NAME)-release_win32.zip; $(APPVEYOR_REPO_TAG_NAME)-debug_win32.zip
  draft: true
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true
