sudo: enabled
dist: trusty
language: cpp
os:
- linux
compiler:
- gcc
before install:
- sudo apt-get -qq update
env:
  matrix:
  - BUILD_CONFIG='release' BUILD_DIR='build_release' RELEASE_NAME='release'
  - BUILD_CONFIG='debug' BUILD_DIR='build_debug' RELEASE_NAME='debug'
script:
- "./configure --config=${BUILD_CONFIG} --dir=${BUILD_DIR} && cd ${BUILD_DIR} && make
  && cd ..;"
before_deploy:
- if [ -n "${RELEASE_NAME}" ]; then 
  cp ./${BUILD_DIR}/ca-lite ./;
  chmod +x ca-lite;
  chmod +x install_dependencies.sh; 
  chmod +x gen_key.sh;
  chmod +x allow_keys2001.sh;
  tar -cvzf ${TRAVIS_TAG}-${RELEASE_NAME}_linux-amd64.tar.gz ca-lite install_dependencies.sh gen_key.sh allow_keys2001.sh;
  fi
deploy:
  provider: releases
  api_key:
    secure: WGSWXRjkaOl+uwJAFdQ5Fe/b4H1T57A/4W+ATWaQ4hIp7o3Dd8nUV7I90aFVlw0dyHFfibla7Qfu+gT3tkex+KBib+lbG5llQYHt0Jn06Vw/Lx71irUxyuiFl9bAVIm9RK16HKf6XSTDujq5DUDge5/BegRyGCqFYu0mCFlYLwvd/pLPPKad2JTNCrpWONzlg/U8FsPNtPP2tAaEUV7fuhXB5qLTl4NSoKb1lcEPBONviLHOFnRkChGywbfTUGHipTBW541tUZr8PFWoMZO61pcY0Xc46Gtg2uXJYv9+cPwmVQb579WfG7U5aAc+Fu55x7i+su55HrJKwD61Z7d7jyUUymq5sdbZxgfZ+sTat2vqJuCiLLObR/F7lEuDl02PsUO1gIgh9/kOJekN/N4NeRji7teVD2QuTz30FIBQ7NBthzMLFLCHR2a2zZECiCKITH1WbxDs8KnsShcTsqoCh93mK7cvKFXHKlKG2xMK92wxybyG7so556av2Yet4vM8Z2WkI+qY87cdfmcNyPFo5zu+1HFN/xwipfKAEW6FbcmER7w+yUDXWaU4RIsgkBsBMlun6n+X/DdZ0/GAMUtiZEaAspqF/Zu5k/ApyGkHutsr/jgHgg+W6kYA5m2JDXqjcmbP1B3pLBQ2iXqYPN1y1Qz/bfXVmMPiniPqjSopRGU=
  skip_cleanup: true
  file:
    - "${TRAVIS_TAG}-release_linux-amd64.tar.gz"
    - "${TRAVIS_TAG}-debug_linux-amd64.tar.gz"
  on:
    tags: true
    repo: fullincome/ca-lite
